cs_CZ = {
    'windowTitle': 'Afinní šifra',
    'typeTitle': 'Typ',
    'naive': 'Naivní',
    'modern': 'Moderní',
    'choseAbc': 'Vyberte abecedu',
    'basicAbc': 'Základní',
    'extAbc': 'Rozšířená',
    'customAbc': 'Vlastní',
    'textHere':'Zde pište text',
    'textChoseFile' : 'Soubor nevybrán',
    'buttonChoseFile' : 'Procházzet soubory',
    'textFile' : 'Text',
    'fileText' : 'Soubor',
    'textShift' : 'Posun o: ',
    'textSpaces' : 'Mezery nahradit pomocí: ',
    'repSpc': 'Bez mezer',
    'repSpcIndx5': 'Vlastní',
    'textOutSpaces' : 'Dělit zašifrovaný text po ',
    'textOutSpaces2' : 'mezerách',
    'textEncode' : 'Šifrovat',
    'textDecode' : 'Dešifrovat',
    'makeCircle' : 'Vytvořit vlastní abecedu',
    'alphabetHere' : 'Abeceda zde (bez konce řádku a čárek)',
    'textKeySensitive' : 'Rozlišit velikost písmen',
    'makeAbc' : 'Vytvořit abecedu',
    'abcWar' : 'Abecada nesmí obsahovat duplicitní znaky.',
    'abcWar2' : 'Abeceda musí obsahovat aspoň 8 znaků',
    'opTextErr' : 'Chyba vstupu',
    'noFileErr' : 'Chyba: Vstupní soubor chybí.',
    'noTextErr' : 'Chyba: Vstupní text chybí.',
    'alphaErr' : 'Mimo abecedu',
    'noCharErr' : 'Znak pro mezery není v abecedě',
    'makeCustomAlpha' : 'Zpět na tvorbu vlastní abecedy',
    'finish' : 'Dokončit',
    'whatYouDo' : 'Co chcete udělat?',
    'whatDoTxt1' : 'Znak "',
    'whatDoTxt2' : '" není v abecedě.',

    'whatDo': ["Odstranit", "Přidat znak", "Nahradit"],
    }